#language: "en"

#pipeline: spacy_sklearn



language: en
pipeline:
- name: "ner_duckling_http"
  url: "http://localhost:8000"
  dimensions: ["time"]
  locale: "en_GB"
  timezone: "Europe/London"
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_spacy"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"

